const char *help = "usage: cryptutil [options].\n\n"
"Available options:\n"
"-help:           \tPrint this help message.\n"
"-in [FILE]:      \tInput file.\n"
"-out [FILE]:     \tOutput file.\n"
"-encrypt:        \tPerform AES encryption.\n"
"-decrypt:        \tPerform AES decryption.\n"
"-encode:         \tBase64 encode the output before saving to output file.\n"
"-decode:         \tBase64 decode the input before any other operation.\n"
"-rsa_encrypt:    \tPerform RSA encryption.\n"
"-rsa_decrypt:    \tPerform RSA decryption.\n"
"-sign:           \tSign input file.\n"
"-verify:         \tPerform RSA signature verification.\n"
"-signature [FILE]\tSignature file.\n"
"-key [FILE]:     \tRequired RSA key for selected operation.\n"
"-silent          \tDo not print output";